### ISSUE TITLE
Not emitting files from top of basedir

### ISSUE THREAD

**Issue by durkes** [andrewrk/node-findit#1]
While trying findit2, I realized that the 'file' event is not emitted for files within the top of basedir. For example:
files/one.txt
files/subdir/two.txt

The file event is only emitted for two.txt since it is in a sub dir, but one.txt is skipped. Is this the intended behavior?

Thank you.

**Comment by andrewrk** [comment]
May I see some example code that exhibits this behavior? I am not observing this problem with my own code.

**Comment by durkes** [comment]
Please forgive me! The problem was occurring because I was adding the file listener late - it was added in time for the sub dirs by chance, but not in time to catch the file events from the top dir. Problem solved. Hopefully I did not waste much of your time looking into this.

Thanks again

**Comment by andrewrk** [comment]
No problem.
